# Scikit-Learn Exercise
## Boston House Prices

Due November 18th

Solutions will be posted on November 17th

In [1]:
#load required packages
import pandas as pd
import numpy as np
from sklearn import datasets, linear_model, metrics, model_selection
import matplotlib.pyplot as plt

In [14]:
#load boston house prices dataset
boston = datasets.load_boston()
boston_df = pd.DataFrame(boston.data, columns=boston.feature_names)
#add the outcome variable, median home value
boston_df['MEDV'] = boston.target
boston_df.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  MEDV  
0     15.3  396.90   4.98  24.0  
1     17.8  396.90   9.14  21.6  
2     17.8  392.83   4.03  34.7  
3     18.7  394.63   2.94  33.4  
4     18.7  396.90   5.33  36.2

In [31]:
#columns of the dataframe
boston_df.columns

Index(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX',
       'PTRATIO', 'B', 'LSTAT', 'MEDV'],
      dtype='object')

### Data Dictionary

* CRIM per capita crime rate by town
* ZN proportion of residential land zoned for lots over 25,000 sq.ft.
* INDUS proportion of non-retail business acres per town
* CHAS Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
* NOX nitric oxides concentration (parts per 10 million)
* RM average number of rooms per dwelling
* AGE proportion of owner-occupied units built prior to 1940
* DIS weighted distances to five Boston employment centres
* RAD index of accessibility to radial highways
* TAX full-value property-tax rate per \$10,000
* PTRATIO pupil-teacher ratio by town
* B 1000(Bk - 0.63)^2 where Bk is the proportion of blacks by town
* LSTAT % lower status of the population
* MEDV Median value of owner-occupied homes in $1000’s

#### 1. Create one NumPy for input variables (everything except for MEDV) and one for the outcome variable (MEDV)

In [5]:
#load required packages
import pandas as pd
import numpy as np
from sklearn import datasets, linear_model, metrics, model_selection
import matplotlib.pyplot as plt

In [9]:
import numpy as np
boston = datasets.load_boston()
boston_df = pd.DataFrame(boston.data, columns=boston.feature_names)
#add the outcome variable, median home value
boston_df['MEDV'] = boston.target
boston_df.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  MEDV  
0     15.3  396.90   4.98  24.0  
1     17.8  396.90   9.14  21.6  
2     17.8  392.83   4.03  34.7  
3     18.7  394.63   2.94  33.4  
4     18.7  396.90   5.33  36.2

In [26]:
#make numpy arrays 
X = np.array(boston_df[['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX',
       'PTRATIO', 'B', 'LSTAT']])
Y = np.array(boston_df['MEDV'])

#### 2. Use train_test_split from the model selection module to divide the data into a test and training set with a test size of 0.2 (use random_state=1)

In [28]:
X_train,X_test, y_train, y_test = model_selection.train_test_split(X, Y, test_size=0.2, random_state=1)

#### 3. Use sklearn linear regression to model the median value of owner-occupied homes on the input variables

In [39]:
sk_linear = linear_model.LinearRegression().fit(X_train,y_train)

#### 4. What are the coefficients and intercept for the model?

In [40]:
sk_linear.coef_

array([-1.12386867e-01,  5.80587074e-02,  1.83593559e-02,  2.12997760e+00,
       -1.95811012e+01,  3.09546166e+00,  4.45265228e-03, -1.50047624e+00,
        3.05358969e-01, -1.11230879e-02, -9.89007562e-01,  7.32130017e-03,
       -5.44644997e-01])

In [41]:
sk_linear.intercept_

42.93352585337743

#### 5. What is the R-squared value for the model on training data? On test data?

In [42]:
sk_linear.score(X_train,y_train)

0.7293585058196337

In [43]:
sk_linear.score(X_test,y_test)

0.7634174432138463

#### 6. Get the model predictions for both the training and test data

In [52]:
Y_pred_train = sk_linear.predict(X_train)
Y_pred_train

array([25.07691032, 21.94177431,  8.36935863, 21.32567191, 15.91001746,
       32.48535453, 24.68497569, 25.22195448, 38.76527526, 29.06426326,
       14.68603541, 35.12938868, 36.02212556, 33.01884229, 21.1045147 ,
       16.59974392, 34.49853101, 39.68765074, 21.52705868, 15.53650416,
       27.46562923, 18.84958341, 27.28595457, 21.30024637, 25.82952228,
       22.24094321, 23.47429214, 28.32611729, 20.4927313 , 24.06521173,
       29.33810041, 10.48469113, 27.09525517, 32.76616554, 13.9858377 ,
       13.46323965, 33.6535524 , 13.45527545, 17.55979769, 16.27322623,
       17.36504291, 28.62361961, 33.90152785, 20.26067325, 24.64254741,
       17.28096122, 28.51721023, 20.38388569, 34.3154568 , 13.83017785,
       19.54869064, 18.94587417, 19.73597208, 31.92356762, 16.35001714,
       28.46695648, 22.89277528, 29.30126344, 34.06551988, 35.2927157 ,
       23.87393548, 18.35466948, 19.23218169, 20.93991203, 26.05181731,
       15.51261458, 15.35628976, 26.22642553, 22.22914856, 17.97

In [54]:
Y_pred_test = sk_linear.predict(X_test)
Y_pred_test

array([32.65503184, 28.0934953 , 18.02901829, 21.47671576, 18.8254387 ,
       19.87997758, 32.42014863, 18.06597765, 24.42277848, 27.00977832,
       27.04081017, 28.75196794, 21.15677699, 26.85200196, 23.38835945,
       20.66241266, 17.33082198, 38.24813601, 30.50550873,  8.74436733,
       20.80203902, 16.26328126, 25.21805656, 24.85175752, 31.384365  ,
       10.71311063, 13.80434635, 16.65930389, 36.52625779, 14.66750528,
       21.12114902, 13.95558618, 43.16210242, 17.97539649, 21.80116017,
       20.58294808, 17.59938821, 27.2212319 ,  9.46139365, 19.82963781,
       24.30751863, 21.18528812, 29.57235682, 16.3431752 , 19.31483171,
       14.56343172, 39.20885479, 18.10887551, 25.91223267, 20.33018802,
       25.16282007, 24.42921237, 25.07123258, 26.6603279 ,  4.56151258,
       24.0818735 , 10.88682673, 26.88926656, 16.85598381, 35.88704363,
       19.55733853, 27.51928921, 16.58436103, 18.77551029, 11.13872875,
       32.36392607, 36.72833773, 21.95924582, 24.57949647, 25.14

#### 7. What is the mean squared error on training data? On test data?

In [56]:
metrics.mean_squared_error(y_train,Y_pred_train)

21.86279471487961

In [58]:
metrics.mean_squared_error(y_test,Y_pred_test)

23.380836480270315